### ISSUE TITLE
User can view list of Harry Potter Characters

### ISSUE THREAD

**Issue by bryan-jun** [bryan-jun/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of Harry Potter characters.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to browse through all of the characters in Harry Potter, seeing their pictures and names. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/61750728/152919783-b1eabfd4-8843-4a34-9038-1d76f7fb0bae.png)
![image](https://user-images.githubusercontent.com/61750728/152919804-3e969866-0426-4de9-acab-aa9b80a1b5e2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="main-view"]` to the HTML.
- [x] Create top nav bar with "Harry Potter Characters" 
- [x] Add a button to go to favorites view 
- [x] Add drop down filter option 
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] make an API call to bring in character data for all characters with house != blank 
- [x] Create DOM of UL that pulls in images and names of all characters
- [x] Have DOM display properly on page 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
